spring:
  profiles: dev
  datasource:
    username: db2admin
    password: Test1234=
    url: jdbc:db2://localhost:50000/spring
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.DB2Dialect




